Logical: ResMed_AVX_SessionData
Id: resmed-avx-session-data
Title: "ResMed AirView Exchange (AVX) Session Data"
Description: """
Source logical model describing the JSON structure of the ResMed AVX API response
for GET /v1/patients/{ecn}/data/sessions/{date}.
Used as source for StructureMaps transforming ResMed data into T-CABS FHIR profiles.
Based on AVX API Technical Specification for Data Collection and Usage (Release 4.38).
"""

* ecn 1..1 string "EasyCare Number" "Patient unique identifier (UUID)"
* totalUsageHoursOnDevice 0..1 string "Total Usage Hours" "Total usage duration in hours since last device reset"

* sessionData 0..* BackboneElement "Session Data" "Array of session records for the patient"

  * receiptTime 1..1 string "Receipt Time" "System time of data receipt to AirView (YYYY-MM-DDThh:mm:ss.sss)"
  * sessionDate 1..1 string "Session Date" "The day this data is for (YYYY-MM-DD)"

  * deviceID 1..1 BackboneElement "Device ID" "Device used by patient on this day"
    * device 1..1 BackboneElement "Device" "Device information"
      * serialNo 1..1 string "Serial Number" "Serial number of the device"
      * deviceType 1..1 string "Device Type" "ResMed device type code (e.g. 026001)"
      * deviceTypeDesc 1..1 string "Device Type Description" "Human-readable device name (e.g. S9 AutoSet)"

  * mode 1..1 string "Therapy Mode" "Therapy mode the device was in (e.g. CPAP, AutoSet, ASV)"

  * usage 1..1 BackboneElement "Usage" "Usage statistics for this session"
    * duration 1..1 string "Duration" "Total usage duration in minutes"
    * maskOn 0..* string "Mask On Times" "Array of mask-on timestamps (YYYY-MM-DD_HH:MM:SS)"
    * maskOff 0..* string "Mask Off Times" "Array of mask-off timestamps (YYYY-MM-DD_HH:MM:SS)"
    * programNumber 0..1 string "Program Number" "Program number (Astral devices only)"
    * programUsage 0..1 string "Program Usage" "Usage in minutes for this program (Astral devices only)"

  * set 0..1 BackboneElement "Settings" "Device settings for this session"
    * press 0..1 string "Pressure" "Set pressure in cmH2O"
    * IPAP 0..1 string "IPAP" "Inspiratory Positive Airway Pressure setting in cmH2O"
    * EPAP 0..1 string "EPAP" "Expiratory Positive Airway Pressure setting in cmH2O"
    * maxPress 0..1 string "Max Pressure" "Maximum allowable pressure in cmH2O"
    * minPress 0..1 string "Min Pressure" "Minimum allowable pressure in cmH2O"
    * maxIPAP 0..1 string "Max IPAP" "Maximum IPAP setting in cmH2O"
    * startEPAP 0..1 string "Start EPAP" "Start EPAP pressure in cmH2O (Stellar only)"
    * minEPAP 0..1 string "Min EPAP" "Minimum EPAP setting in cmH2O"
    * maxEPAP 0..1 string "Max EPAP" "Maximum EPAP setting in cmH2O"
    * minPS 0..1 string "Min Pressure Support" "Minimum Pressure Support in cmH2O"
    * maxPS 0..1 string "Max Pressure Support" "Maximum Pressure Support/P Control Max in cmH2O"
    * EPRType 0..1 string "EPR Type" "Expiratory Pressure Relief type"
    * EPRLevel 0..1 string "EPR Level" "Expiratory Pressure Relief level"
    * tidalVolume 0..1 string "Tidal Volume" "Tidal Volume setting in mL"
    * Ti 0..1 string "Ti" "Inspiratory time setting in seconds (Stellar/Astral only)"
    * tiMin 0..1 string "Ti Min" "Ti Min setting in seconds (Stellar/Astral only)"
    * tiMax 0..1 string "Ti Max" "Ti Max setting in seconds (Stellar/Astral only)"
    * respRate 0..1 string "Respiratory Rate" "Respiratory Rate/Backup Rate in breaths per minute (Stellar/Astral only)"
    * backupRate 0..1 string "Backup Rate" "Backup respiratory rate in breaths per minute"
    * interface 0..1 string "Interface" "Patient Interface Type: Invasive, Mask, Mouthpiece"
    * mask 0..1 string "Mask" "Mask Type: FullFace, Nasal, NasalUltra, Pillows, etc. (Stellar/Astral only)"
    * circuit 0..1 string "Circuit" "Breathing Circuit Type: SingleValved, DualValved, SingleVented, MouthpieceCircuit"

  * clinicalMetrics 0..1 BackboneElement "Clinical Metrics" "Clinical metrics over the session (percentiles)"
    * tgtIPAP 0..1 BackboneElement "Target IPAP" "Target IPAP metrics (cmH2O)"
      * p5 0..1 string "5th Percentile" "5% of target IPAP"
      * p50 0..1 string "Median" "Median target IPAP"
      * p95 0..1 string "95th Percentile" "95% of target IPAP"
      * max 0..1 string "Maximum" "Maximum target IPAP"
    * tgtEPAP 0..1 BackboneElement "Target EPAP" "Target EPAP metrics (cmH2O)"
      * p5 0..1 string "5th Percentile" "5% of target EPAP"
      * p50 0..1 string "Median" "Median target EPAP"
      * p95 0..1 string "95th Percentile" "95% of target EPAP"
      * max 0..1 string "Maximum" "Maximum target EPAP"
    * leak 0..1 BackboneElement "Leak" "Leak metrics (L/s)"
      * p50 0..1 string "Median" "Median leak"
      * p95 0..1 string "95th Percentile" "95% of leak"
      * max 0..1 string "Maximum" "Maximum leak"
    * respRate 0..1 BackboneElement "Respiratory Rate" "Respiratory rate metrics (/min)"
      * p5 0..1 string "5th Percentile" "5% of respiratory rate"
      * p50 0..1 string "Median" "Median respiratory rate"
      * p95 0..1 string "95th Percentile" "95% of respiratory rate"
      * max 0..1 string "Maximum" "Maximum respiratory rate"
    * ieRatio 0..1 BackboneElement "I:E Ratio" "Inhalation:exhalation ratio metrics"
      * p5 0..1 string "5th Percentile" "5% of I:E ratio"
      * p50 0..1 string "Median" "Median I:E ratio"
      * p95 0..1 string "95th Percentile" "95% of I:E ratio"
      * max 0..1 string "Maximum" "Maximum I:E ratio"
    * minuteVent 0..1 BackboneElement "Minute Ventilation" "Minute ventilation metrics (L/min)"
      * p5 0..1 string "5th Percentile" "5% of minute ventilation"
      * p50 0..1 string "Median" "Median minute ventilation"
      * p95 0..1 string "95th Percentile" "95% of minute ventilation"
      * max 0..1 string "Maximum" "Maximum minute ventilation"
    * tidalVol 0..1 BackboneElement "Tidal Volume" "Tidal volume metrics (L)"
      * p5 0..1 string "5th Percentile" "5% of tidal volume"
      * p50 0..1 string "Median" "Median tidal volume"
      * p95 0..1 string "95th Percentile" "95% of tidal volume"
      * max 0..1 string "Maximum" "Maximum tidal volume"
    * SPO2 0..1 BackboneElement "SpO2" "Oxygen saturation metrics (%)"
      * min 0..1 string "Minimum" "Minimum SpO2"
      * p5 0..1 string "5th Percentile" "5% of SpO2"
      * p50 0..1 string "Median" "Median SpO2 (50th percentile)"
      * p95 0..1 string "95th Percentile" "95% of SpO2"
      * minutesBelow88percent 0..1 string "Minutes Below 88%" "Minutes SpO2 was below 88%"
      * secondsBelowDynamicThreshold 0..1 string "Seconds Below Dynamic Threshold" "SpO2 seconds below dynamic threshold"

  * respEvents 0..1 BackboneElement "Respiratory Events" "Respiratory event indices per hour"
    * AHI 0..1 string "AHI" "Apnea-Hypopnea Index (events/hour)"
    * AI 0..1 string "AI" "Apnea Index (events/hour)"
    * HI 0..1 string "HI" "Hypopnea Index (events/hour)"
    * OAI 0..1 string "OAI" "Obstructive Apnea Index (events/hour)"
    * CAI 0..1 string "CAI" "Central Apnea Index (events/hour)"
    * UAI 0..1 string "UAI" "Unknown Apnea Index (events/hour)"
    * ODI 0..1 string "ODI" "Oxygen Desaturation Index"
    * CSR 0..1 string "CSR" "Cheyne-Stokes Respiration (minutes)"
    * RERA 0..1 string "RERA" "Respiratory Effort Related Arousal (events/hour)"

  * spontTriggBreaths 0..1 string "Spontaneous Triggered Breaths" "Percentage of spontaneous triggered breaths"
  * spontCycledBreaths 0..1 string "Spontaneous Cycled Breaths" "Percentage of spontaneous cycled breaths"
